version: 2.1

jobs:
  run-test:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - run: node --version
      - run:
          name: "Install packages"
          command: "npm ci --no-audit --prefer-offline"
      - run:
          name: "Install playwright deps"
          command: "sudo npx playwright install-deps"
      - run:
          name: "Install Playwright"
          command: "npx playwright install"
      - run:
          name: "Run tests"
          command: "npm run test"

workflows:
  ci-workflow:
    jobs:
      - run-test